import { randomUUID } from 'node:crypto';
import { mkdir, readdir, readFile, rename, rm, unlink, writeFile } from 'node:fs/promises';
import { hostname } from 'node:os';
import { dirname, join } from 'node:path';
import { processImage } from './AssetImage.ts';
import { assetSourceBytes, assetToolchain } from './AssetInputs.ts';
import { withAssetLock } from './AssetLock.ts';
import { type AssetRecipe, assetPath, readRecipe, sha256, stableJson } from './AssetRecipe.ts';

interface RuntimeAsset {
  id: string;
  file: string;
  hash: string;
  width: number;
  height: number;
}
export interface RuntimeBuild {
  schemaVersion: 1;
  fingerprint: string;
  inputsFingerprint: string;
  directory: string;
  registryHash: string;
  toolchain: Record<string, string>;
  assets: RuntimeAsset[];
}

async function inputs(root: string): Promise<AssetRecipe[]> {
  const path = await assetPath(root, 'assets/metadata/runtime-sentinel.json', 'assets/metadata');
  let names: string[];
  try {
    names = await readdir(dirname(path));
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return [];
    throw error;
  }
  const recipes: AssetRecipe[] = [];
  for (const name of names.sort()) {
    if (!name.endsWith('.json')) continue;
    const { recipe } = await readRecipe(root, name.slice(0, -5));
    if (recipe.state === 'active') {
      await assetSourceBytes(root, recipe);
      recipes.push(recipe);
    }
  }
  return recipes;
}

/** A dead local process is recoverable; age, foreign hosts and permission errors are not proof. */
async function liveDev(root: string): Promise<boolean> {
  const path = await assetPath(root, 'reports/assets/dev-server.json', 'reports/assets');
  let owner: { pid: number; host: string; token: string };
  try {
    owner = JSON.parse(await readFile(path, 'utf8'));
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return false;
    throw new Error(
      'Invalid dev-server marker: inspect reports/assets/dev-server.json before rebuilding.',
    );
  }
  if (
    !Number.isInteger(owner.pid) ||
    owner.pid <= 0 ||
    typeof owner.token !== 'string' ||
    typeof owner.host !== 'string'
  )
    throw new Error('Invalid dev-server marker.');
  if (owner.host !== hostname()) return true;
  try {
    process.kill(owner.pid, 0);
    return true;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ESRCH') return true;
    await unlink(path);
    return false;
  }
}

function registry(build: Pick<RuntimeBuild, 'fingerprint' | 'directory' | 'assets'>): string {
  return [
    `// MGD runtime generation: ${build.fingerprint}`,
    '// Generated by assets:build. Edit assets/metadata recipes instead.',
    ...build.assets.flatMap((asset, index) => [
      `import asset${index} from ${JSON.stringify(`../../${build.directory}/${asset.file}?no-inline`)};`,
      `export const ASSET_${asset.id.replace(/-/g, '_').toUpperCase()} = { url: asset${index}, width: ${asset.width}, height: ${asset.height} } as const;`,
    ]),
    'export {};',
    '',
  ].join('\n');
}

async function readPublished(root: string): Promise<RuntimeBuild> {
  const text = await readFile(
    await assetPath(root, 'src/generated/assets.ts', 'src/generated'),
    'utf8',
  );
  const fingerprint = /^\/\/ MGD runtime generation: ([a-f0-9]{64})\n/.exec(text)?.[1];
  if (!fingerprint) throw new Error('Runtime registry is missing its generation identity.');
  const directory = `assets/processed/mgd/${fingerprint}`;
  const build = JSON.parse(
    await readFile(
      await assetPath(root, `${directory}/generation.json`, 'assets/processed'),
      'utf8',
    ),
  ) as RuntimeBuild;
  if (
    build.schemaVersion !== 1 ||
    build.fingerprint !== fingerprint ||
    build.directory !== directory ||
    !Array.isArray(build.assets) ||
    sha256(text) !== build.registryHash ||
    text !== registry(build)
  )
    throw new Error('Runtime generation or registry is damaged. Run assets:build.');
  for (const asset of build.assets) {
    if (
      !/^[a-z0-9]+(?:-[a-z0-9]+)*\.(png|jpg|webp)$/.test(asset.file) ||
      asset.file !== `${asset.id}.${asset.file.split('.').pop()}`
    )
      throw new Error('Invalid runtime media path.');
    if (
      sha256(
        await readFile(await assetPath(root, `${directory}/${asset.file}`, 'assets/processed')),
      ) !== asset.hash
    )
      throw new Error(`Runtime output damaged: ${asset.id}. Run assets:build.`);
  }
  return build;
}

export async function readRuntimeBuild(root: string): Promise<RuntimeBuild> {
  const build = await readPublished(root);
  if (sha256(stableJson(await inputs(root))) !== build.inputsFingerprint)
    throw new Error('Runtime inputs changed. Run assets:build.');
  const current = await assetToolchain(root, 'runtime');
  const { runtime: _currentRuntime, ...currentNative } = current;
  const { runtime: _recordedRuntime, ...recordedNative } = build.toolchain;
  if (stableJson(currentNative) !== stableJson(recordedNative))
    throw new Error('Runtime toolchain changed. Run assets:build.');
  return build;
}

/** Remove only files listed by a previous builder generation, preserving unknown files. */
async function cleanPrevious(
  root: string,
  previous: RuntimeBuild | undefined,
  current: string,
): Promise<void> {
  if (!previous || previous.fingerprint === current) return;
  const path = await assetPath(root, `${previous.directory}/generation.json`, 'assets/processed');
  for (const file of [...previous.assets.map((asset) => asset.file), 'generation.json'])
    await rm(join(dirname(path), file), { force: true });
  if ((await readdir(dirname(path))).length === 0) await rm(dirname(path), { recursive: true });
}

/** Caller holds the shared asset lock until its consumer has finished. */
export async function buildRuntimeLocked(
  root: string,
  signal?: AbortSignal,
): Promise<RuntimeBuild> {
  const dev = await liveDev(root);
  try {
    return await readRuntimeBuild(root);
  } catch {
    /* Build or repair the complete active set. */
  }
  if (dev)
    throw new Error(
      'Runtime assets changed while a dev server is running. Stop the dev server, then rebuild/restart.',
    );
  const recipes = await inputs(root);
  const toolchain = await assetToolchain(root, 'runtime');
  const inputsFingerprint = sha256(stableJson(recipes));
  const fingerprint = sha256(stableJson({ recipes, toolchain }));
  const directory = `assets/processed/mgd/${fingerprint}`;
  const staging = await assetPath(
    root,
    `reports/assets/runtime-staging-${randomUUID()}/generation.json`,
    'reports/assets',
  );
  const destination = await assetPath(root, `${directory}/generation.json`, 'assets/processed');
  const registryPath = await assetPath(root, 'src/generated/assets.ts', 'src/generated');
  let previous: RuntimeBuild | undefined;
  try {
    previous = await readPublished(root);
  } catch {
    /* First build or damaged previous generation. */
  }
  await mkdir(dirname(staging), { recursive: true });
  try {
    const assets: RuntimeAsset[] = [];
    for (const recipe of recipes) {
      signal?.throwIfAborted();
      const image = await processImage(await assetSourceBytes(root, recipe), recipe);
      const file = `${recipe.id}.${image.extension}`;
      await writeFile(join(dirname(staging), file), image.bytes);
      assets.push({
        id: recipe.id,
        file,
        hash: sha256(image.bytes),
        width: image.output.width,
        height: image.output.height,
      });
    }
    const build: RuntimeBuild = {
      schemaVersion: 1,
      fingerprint,
      inputsFingerprint,
      directory,
      toolchain,
      assets,
      registryHash: '',
    };
    const text = registry(build);
    build.registryHash = sha256(text);
    await writeFile(staging, `${stableJson(build)}\n`);
    if (
      sha256(stableJson(await inputs(root))) !== inputsFingerprint ||
      stableJson(await assetToolchain(root, 'runtime')) !== stableJson(toolchain)
    )
      throw new Error('Runtime inputs changed during processing; nothing published.');
    signal?.throwIfAborted();
    await mkdir(dirname(dirname(destination)), { recursive: true });
    // Same-identity repair is guarded against live consumers by the shared lock and dev marker.
    try {
      await rename(dirname(staging), dirname(destination));
    } catch (error) {
      if (!['EEXIST', 'ENOTEMPTY'].includes((error as NodeJS.ErrnoException).code ?? ''))
        throw error;
      for (const file of [...assets.map((asset) => asset.file), 'generation.json'])
        await rename(join(dirname(staging), file), join(dirname(destination), file));
    }
    await mkdir(dirname(registryPath), { recursive: true });
    const temporary = `${registryPath}.${randomUUID()}.tmp`;
    try {
      await writeFile(temporary, text);
      await rename(temporary, registryPath);
    } finally {
      await rm(temporary, { force: true });
    }
    await cleanPrevious(root, previous, fingerprint);
    return await readRuntimeBuild(root);
  } finally {
    await rm(dirname(staging), { recursive: true, force: true });
  }
}

export async function buildRuntime(
  root: string,
  options: { signal?: AbortSignal } = {},
): Promise<RuntimeBuild> {
  await assetPath(root, 'reports/assets/.write-lock/owner.json', 'reports/assets');
  return withAssetLock(root, () => buildRuntimeLocked(root, options.signal), options);
}
